server:
  port: 8080

spring:
  jackson.deserialization:
      fail-on-unknown-properties: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 3000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: orders-ms
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.develop.core.*

order.events.topic.name: orders-events